new project
MaryLakhanich/FinalSurge_Diploma_Maria_Lakhanich pull request #1
Opened 2022-09-04 19:53 UTC by MaryLakhanich

2022-09-04 20:07 UTC, voropa requested changes

2022-09-04 20:07 UTC, voropa commented on src/test/java/pages/DailyVitalsPage.java
> +    private final static By STEPS_LOCATOR = By.xpath("//table[@class='table table-striped table-condensed']//tr//td[2]");
td[2] - выглядит не надежно)

2022-09-04 20:07 UTC, voropa commented on src/test/java/pages/LoginPage.java
> +    public void Login(String email, String password) {
названия методов с меленькой буквы

2022-09-04 20:07 UTC, voropa commented on src/test/java/pages/WorkoutDetailsPage.java
> +    private static final By ACTUAL_PERCEIVED_EFFORT = By.xpath("//div[@class='formSep'][3]");
[3] - не надежный локатор

2022-09-04 20:07 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +    protected final static String EMAIL = "amigo-10291@mail.ru";
Вынесите а .properties файл

2022-09-04 20:07 UTC, voropa commented on src/test/java/tests/DailyVitalsTest.java
> +
А где проверки?

2022-09-04 20:07 UTC, voropa commented on src/test/java/tests/TestListener.java
> +        System.out.println("Test " + result.getName() + " started");
Замените system.out на logger.info/debug

2022-09-16 19:37 UTC, voropa requested changes

2022-09-16 19:37 UTC, voropa commented on src/test/java/modals/CaloricNeedsCalculatorModal.java
> +        new Input(driver).setValue(WEIGHT, "70");
Почему тестовые данные захардкоданы прямо в методе? Они должны передаваться сюда входными аргументами

2022-09-16 19:37 UTC, voropa commented on src/test/java/modals/PaceCalculatorModal.java
> +        new Input(driver).setValue(DISTANCE, "10");
То же самое тут

2022-09-16 19:37 UTC, voropa commented on src/test/java/modals/PrintModal.java
> +        new Input(driver).setValue(STARTING_DATE,"08/28/2022");
И тут

2022-09-16 19:37 UTC, voropa commented on src/test/java/pages/DailyVitalsPage.java
> +    private static final By LAST_DATE_IN_TABLE = By.xpath("//table[contains(@class,'table-striped')]/tbody/tr[1]/td[1]");
А там точно таблица не динамическая и колличество строк всегда одинаковое? В противном случае ваши локаторы не сработают, если таблица расширится в какой-то момент

2022-09-16 19:37 UTC, voropa commented on src/test/java/pages/PrintPage.java
> +        WebElement element = driver.findElement(By.xpath("//a[contains(@href, 'print')]"));
У вас же уже есть этот локатор выше PTINT_BUTTON, зачем его писать еще раз?
И удалите закоментированную строку

2022-09-16 19:37 UTC, voropa commented on src/test/java/pages/TrainingPlansPage.java
> +        js.executeScript("arguments[0].click()", button);
Так как у вас в нескольких метсах используется клик через javascript, то имеет смысл вынести это в отдельный метод в base классе

2022-09-16 19:37 UTC, voropa commented on src/test/java/tests/OtherCalculatorsTest.java
> +        homePage.switchToIframe();
Почему не делааете switchToDefaultContent, после того, как сделали необходимые действия внутри iFframe?

2022-09-16 19:37 UTC, voropa commented on src/test/java/tests/PrintWorkoutsTest.java
> +        driver.switchTo().defaultContent();
В тестовых сценариях не должно быть работы с драйвером напрямую. Вынесите это действие в метод в page классе

2022-09-16 19:37 UTC, voropa commented on src/test/java/tests/PrintWorkoutsTest.java
> +        Assert.assertTrue(printPage.isPageOpened());
Проверки что страница открылась недостаточно, нужно проверить, что на этой странице хотя бы присутсвует необходимая ожидаемая информация

2022-09-18 18:38 UTC, MaryLakhanich commented on src/test/java/pages/DailyVitalsPage.java
> +    private static final By LAST_DATE_IN_TABLE = By.xpath("//table[contains(@class,'table-striped')]/tbody/tr[1]/td[1]");
Последняя дата выбранного периода всегда находится в ячейке [1][1], первая дата в таблице отображается в последней строке, для определения номера строки ввела определение по индексу в зависимости от количества таких элементов

2022-09-18 19:47 UTC, voropa approved these changes

2022-09-19 18:51 UTC, merged